name: Build Flutter Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3' # نسخه Flutter مورد نظر خود را مشخص کنید
        channel: 'stable'

    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows app
      run: flutter build windows --release

    - name: Display build directory contents
      run: dir build\windows\x64\runner\Release

    - name: Compress release bundle
      run: |
        Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath windows-release-bundle.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: windows-release-bundle.zip